language: java
jdk: oraclejdk8
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: faUbArsOkprxxRzAYwlm2b3xZeC7m+jc6usBbDVtcpqNpdlhNcO7640mABrapi/aXq12hwvzqfLSq+BSMREhwmB9tfVSHbL5P8pqesKOfEzODlbh4+qKZ6yAn49LOW5snmU9dxa/spkEL3lsWDSrfRlrZhTe5nJ6Jz9ZgAYV2kZTxUcgxrcjXzsSgXTiIARfMpBin6QFk4dQ0YvvlL7ZpwwB0Ok5AFzIWoFXSgfcL0QpVoeyoa/hxAvceIi5GFUI+iiI4PihWoR26Uc0hKkyEf+Tv82qX99ELkNta6eQg6esnjo68mz9shUQ+EjA4YZ+Rkdmv2ygg2bZgru55TG2N51wzFVROnsNJ53qoB5qU9AShl/TzXM6IH6gn0+2BH3GNWZ6naGG2VgMGGSJmJT601IyC+i0cOh2FZ7WJUuv6SYyjVA2moixtJrAJaJ1N4j1b/uWyPf7T2vPYRfy0VOG+GmYEgz2Q4m9nD4SkL4i2Hu6QnSPihBH535LX4+3kqC2Jy/3KTQfBMD+j6ScM4E9wChfQuWKBXZB4+oo1LMVjo9YrV2vEcfRzi6+BnfCIgesn0JJR2UzbbcVxGHigRwd34KS/K050Fc7gB/1BoU5pwR3+kYo8sWqmV/ccOH7sKYu3TNVrCn4Sla/04HqB1xm/BL2m/+D1bI3sJ6GMVe8dh0=
  app: npmbeer-pedibus