version: '3'
services:
    db:
        build:
            context: .
            dockerfile: mongo.dockerfile
        expose:
            - "27017"
        networks:
            - app-network

    backend:
        restart: always
        container_name: backend
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        depends_on:
            - db
        networks:
            - app-network
    frontend:
        restart: always
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - 80:80
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
